### ISSUE TITLE
Support overwrite command to sanitize dimms

### ISSUE THREAD

**Issue by yechun1** [intel/ipmctl#155]
Are we able to add new commend of **overwrite** to sanitize dimm for recovery? Just like **ndctl sanitize -overwrite**?
It would be very help for CSP users to quickly restore the DIMM unrecoverable PCD configuration errors.

**Comment by sscargal** [comment]
@yechun1 The overwrite command writes zero's across the entire memory capacity. 

You don't need to overwrite the entire PMem module to destroy the PCD/LSA. An overwrite is a very time consuming operation and only necessary if you absolutely must overwrite the entire module for security requirements. 

Most of the security features for the OS build of ipmctl are deprecated, though they continue to exist in the UEFI build. There were several reasons for this, primarily because of the privileged WBINVD instruction and because ndctl already had the features.  

Most OEM BIOS releases include the ability to perform a secure erase operation. Some OEMs also implemented the overwrite operation to comply with NIST 800-88 requirements. You can perform a secure erase [with overwrite] manually from the BIOS via a console connection or through orchestration mechanisms such as REST APIs, RedFish, etc. Refer to the OEM documentation for more detailed instructions. Many CSPs take this HW level approach. 

If all you want to do is wipe the PCD/LSA, you can delete the PCD and LSA areas without performing an overwrite operation using `ipmctl delete -dimm -pcd`. The IPMCTL-DELETE-PCD(1) man page has more information. 

OS Walkthrough Example:

```
// For FSDAX and SECTOR namespaces, unmount all filesystems and remove entries from /etc/fstab if applicable
// Skip this for DEVDAX and RAW namespaces
$ sudo umount <fs>

// Destroy all namespaces
$ sudo ndctl destroy-namespace -f all 

// [Optional] List the current PCD/Config
$ sudo ipmctl show -pcd

// Delete the PCD/LSA
$ sudo ipmctl delete -dimm -pcd
WARNING: Modifying the Platform Configuration Data can result in loss of data!
Clear Config partition(s) on 12 PMem module(s).
Do you want to continue? [y/n] y

Clear Config partition(s) on PMem module 0x0001: Success
Clear Config partition(s) on PMem module 0x0011: Success
Clear Config partition(s) on PMem module 0x0021: Success
Clear Config partition(s) on PMem module 0x0101: Success
Clear Config partition(s) on PMem module 0x0111: Success
Clear Config partition(s) on PMem module 0x0121: Success
Clear Config partition(s) on PMem module 0x1001: Success
Clear Config partition(s) on PMem module 0x1011: Success
Clear Config partition(s) on PMem module 0x1021: Success
Clear Config partition(s) on PMem module 0x1101: Success
Clear Config partition(s) on PMem module 0x1111: Success
Clear Config partition(s) on PMem module 0x1121: Success

Data dependencies may result in other commands being affected. A system reboot is required before all changes will take effect.

// [Optional] List the current PCD/Config
$ sudo ipmctl show -pcd

// You should now get the following message from ipmctl and the BIOS
$ sudo ipmctl show -memoryresources
One or more PMem modules have invalid PCD data. A platform reboot is recommended to restore valid PCD data, then try again.
```

There's more information in [How to Securely Erase Data on Intel® Optane™ Persistent Memory](https://software.intel.com/content/www/us/en/develop/articles/how-to-securely-erase-data-on-intel-optane-persistent-memory.html).

If the above information does not solve your initial request, please provide more information about the specific use case.

**Comment by yechun1** [comment]
@sscargal thanks for your information. There are several cases 1) we have PMem devices used on one platform and moved to another platform without delete PCD. 2) we have several dimms with old FW version, and several dimms will newer FW using together. 3) we have AEP used by ipmctl 1.x and after re-install OS and use ipmctl2.x to re-configure. And other random operations that delete PCD/LSA could not work, then create goal will fail. Only use ndctl overwrite could recovery it. Most of the behaviors do not follow Intel documents, but we need to recovery it once error happens.
As ndctl could only support Linux, and only work under AD mode, If set as MM mode, it could not work.
For specific DIMM issues, we have Intel team support. We have checked with several OEMs, they have not yet supported dimm overwrite from BIOS.  
Just thinking about ipmctl, it should be a good feature if ipmctl could support dimm overwrite when dimms are not able to recover by "delete PCD".

**Comment by yechun1** [comment]
If any security related operation is not supported by ipmctl at the OS level, it should be a limitation. We could use ndctl for securely erase. Thanks for support. I'll close this ticket.
