### ISSUE TITLE
Why isn't the endianness swapped for subsystem device ID?

### ISSUE THREAD

**Issue by swiginton** [intel/ipmctl#44]
https://github.com/intel/ipmctl/blob/50b544e98e7dd9b1a70d2c53b266efe46a983173/DcpmPkg/cli/ShowDimmsCommand.c#L770

It is for the device, vendor, and subsystem vendor IDs?

**Comment by juston-li** [comment]
Short answer is that it displays the correct ID 0x97A for DCPMM.

Long answer, there was probably some confusion about this field and so there's a bug in SPD.
Not endian swapping aligns with the JEDEC spec as Byte 192 0x7A is LSB and Byte 193 0x09 is MSB so 0x097A stored little-endian.

Unfortunately, the other fields you mentioned were populated differently. Those are used as an array of bytes for the DIMM UID which is big endian. That's why we do the endian swap, so that it aligns with the UID but that does make it different than what JEDEC LSB/MSB says for VendorIds.
