### ISSUE TITLE
nvm_erase_device doesn't actually call erase

### ISSUE THREAD

**Issue by dchanman** [intel/ipmctl#48]
https://github.com/intel/ipmctl/blob/master/src/os/nvm_api/nvm_management.c#L1630

It appears that nvm_erase_device doesn't actually call erase as the header file implies (ie. setting a zeroed passphrase to cryptographically erase the data).

**Comment by juston-li** [comment]
Issuing secure erase (along with most other security commands) is not supported in OS because WBINVD is required to flush/invalidate caches but that can only be called in kernel context. 

There are patches in review that add support for security DSMs https://patchwork.kernel.org/project/linux-nvdimm/list/?series=24645
